version: '3.1'

services:
  backend:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:47017
  mongo:
    image: mongo
    restart: always
    ports:
      - 47017:27017
    volumes:
      - mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:47017?ssl=false

volumes:
  mongodb:
